=== CritterCodes/To-Do-App/schemas/list.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://myapplication/list.json",
    "title": "List",
    "description": "A to-do list",
    "type": "object",
    "required": ["listID", "name", "createdAt"],
    "properties": {
      "listID": {
        "description": "The unique id for this list -, format: TASK-${shortTask}-${uuid().slice(-4)}",
        "type": "string"
      },
      "name": {
        "description": "The name of this task",
        "type": "string",
        "minLength": 3
      },
      "createdAt": {
        "description": "The date the list was made on.",
        "type": "string"
      },
      "tasks": {
        "description": "The tasks of this list",
        "type": "array"
      },
      "completedTasks": {
        "description": "Completed tasks for this list",
        "type": "array"
      }
    }
  }

=== CritterCodes/To-Do-App/toDoLists/chores.json
{
  "listID": "LIST-chores-7383",
  "name": "chores",
  "createdAt": "2024-03-24T17:37:47.409Z",
  "tasks": [
    {
      "id": "TASK-Swee-a4da",
      "updatedAt": "2024-03-24T18:29:46.935Z",
      "status": "incomplete",
      "color": "red",
      "task": "Mop the kitchen"
    }
  ],
  "completedTasks": []
}

=== CritterCodes/To-Do-App/toDoLists/example.json
{
  "listID": "LIST-example-02a5",
  "name": "example",
  "createdAt": "2024-03-25T13:24:03.633Z",
  "tasks": [],
  "completedTasks": [
    {
      "taskID": "TASK-litt-fa64",
      "createdAt": {
        "updatedAt": "2024-03-25T13:54:13.270Z"
      },
      "status": "completed",
      "color": "green - #00ff00",
      "task": "litter box"
    }
  ]
}
